import os


class Config:
    SQLALCHEMY_DATABASE_URI = os.getenv('DATABASE_URI')
    SQLALCHEMY_TRACK_MODIFICATIONS = False
    SECRET_KEY = os.getenv('SECRET_KEY')

    DEFAULT_SHORT_ID_SIZE = 6
    ORIGINAL_LINK_MAX_SIZE = 256
    SHORT_ID_MAX_SIZE = 16
